import React from 'react';
import { Row, Col } from 'react-bootstrap';
import Header from '../components/Header/customHeader';
import Grow from '@material-ui/core/Grow';

class Terms extends React.Component {
  render() {
    return (
      <Grow in={true} timeout={700}>
        <div style={{ height: '100vh', overflow: 'auto' }}>
          <Header title={'Terms of Use'} backButton backTo={() => this.props.history.push('/')} />
          <div style={{ padding: '20px', marginBottom: '40px' }}>
            <p>
              To facilitate the services/product of Experts (<b>“Expert(s)”</b>) to the investors (<b>“Investor(s)”</b>)
              (the Expert(s) and the Investor(s) are hereinafter together referred to as <b>“Users”/“You”</b>) over
              e-commerce platform of aggregator i.e. www.pvot.in (hereinafter referred to as <b>"Website"</b> which
              expression shall also refer to the mobile application, online portals owned and operated by Pvot).
            </p>
            <p>
              This document (“Terms of Use”) is an electronic record in terms of Information Technology Act, 2000 and
              rules thereunder as applicable and the amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a
              computer system and does not require any physical or digital signatures.
            </p>
            <Row>
              <h6>Definitions -</h6>
            </Row>
            <Row>
              <p>
                <b>“Expert(s)”</b> shall mean any natural person, limited or unlimited liability company, corporation,
                partnership (whether limited or unlimited), proprietorship, Hindu undivided family, trust, union,
                association, government or any agency or political subdivision thereof or any other entity that may be
                treated as a person under Law, who signed up to the Website as an Expert through the sign-up options
                provided on the Website by Pvot
              </p>
              <p>
                <b>“Expertise”</b> shall mean market research data/documents/trading call/tips or any other advise
                provided by the Expert on the Website with relating to investing, purchasing, selling or otherwise
                dealing in securities or investment products or commodities conveyed to the Investors through the
                Website.
              </p>
              <p>
                <b>“Investor(s)”</b> - shall mean any natural person, limited or unlimited liability company,
                corporation, partnership (whether limited or unlimited), proprietorship, Hindu undivided family, trust,
                union, association, government or any agency or political subdivision thereof or any other entity that
                may be treated as a person under Law, who signed up to the Website as an Investor through the sign-up
                options provided on the Website by Pvot
              </p>
              <p>
                <b>“Details”</b> – shall mean all such information related to the Expert operating an Expert profile
                which may include but not limited to the historical analysis of the Expert published by the Expert,
                certificate of registration of the Expert as obtained by the Expert under any applicable law and
                uploaded by the Expert, details of pending complaints against the Expert, contact details of the
                compliance officer of the Expert or any other such information that the Expert shall be required to
                disclose under any applicable law.
              </p>
              <p>
                <b>“Fees”</b> shall mean such consideration that the Investor shall be required to pay for obtaining
                access to near-real time activity of an Expert either through a pre-paid/post-paid/subscription/pay as
                you go model as may be updated and modified at the sole discretion of Pvot
              </p>
              <p>
                <b>“Reference Terms”</b> shall mean all applicable terms and conditions applicable and fully enforceable
                against the Users as included under the Privacy policy, Disclaimer, Risk Disclosure, Cookies policy,
                Website Terms and Conditions etc.
              </p>
              <p>
                <b>“Pvot Policies”</b> shall mean this Terms of Use and the Reference Terms.
              </p>
              <p>
                Use of the Website and its services and tools of Pvot by the Users are governed by Pvot Policies which
                is mandatorily applicable to You. If You transact/act/use Website content/facilitate services, you shall
                be subject to the Pvot Policies that are applicable to you. By mere use of the Website, You shall
                undertake, agree to and confirm that you have understood the content of these Pvot Policies and you are
                contracting with Pvot and the Pvot Policies shall constitute binding obligations on you.
              </p>
              <p>
                We reserve the right, at our sole discretion, to change, modify, add or remove portions ofany of the
                Pvot Policies, at any time without any prior written notice to you. It is your responsibility to review
                these Pvot Policies periodically for updates / changes. Your continued use of the Website deems that you
                accept and agree to the revisions made by us to Pvot Policies. If any change in the Pvot Policies are
                deemed as a major change by Pvot in its sole and absolute discretion then Pvot may notify the changes to
                the Users by way of an email, sms, pop notifications, phone call or any other form of communication Pvot
                deems fit. It is hereby clarified that Pvot has no obligation to notify these changes and the Users have
                the primary responsibility to periodically check the relevant sections of the Website to determine such
                changes.
              </p>
              <p>
                As long as You comply with these Pvot Policies, Pvot grants you a personal, non-exclusive,
                non-transferable, limited privilege to use the Website.
              </p>
              <p>
                If, at any time, You do not wish to accept the Terms and Conditions, you shall not use the Website or
                any other services provided by Pvot governed by the Pvot Policies. Any terms and conditions proposed by
                you which are in addition to, or which conflict with these Terms and Conditions are expressly rejected
                by Pvot and will have no force or effect.
              </p>
            </Row>
            <Row>
              <h6>
                ACCESSING, BROWSING, FACILITATING OR OTHERWISE USING THE WEBSITE INDICATES THAT YOU HAVE AGREED TO ALL
                THE TERMS AND CONDITIONS HEREINUNDER
              </h6>
            </Row>
            <Row>
              <p>
                By impliedly or expressly accepting the Pvot Policies, You undertake and confirm that you accept and
                agree to be bound by Pvot Policies as amended from time to time. This Agreement is for an indefinite
                term and you understand and agree that you are bound by such terms.
              </p>
              <p>
                By using the Website, you agree to follow and are bound by all terms and conditions in connection to use
                of the Website. Certain areas of the Site may have different terms of use posted. If there is a conflict
                between the Terms of Use and terms of use posted for a specific area of the Site, the latter shall have
                precedence with respect to your use of that area of the Site.
              </p>
              <p>
                Pvot does not give/throw/display/sell any advisory for trading on its own or through SMS or by any other
                means. Pvot is only facilitating promotion/services of the Experts. Investors on the Website are free to
                follow or subscribe to any Expert and choose act on any call from any one or more Expert or reject/not
                opt in on any services at their sole discretion. Pvot shall in no event be liable for any loss(es)
                incurred by the user/investor due to any activity of the Expert on the Website. Pvot shall not be liable
                for any damage incurred to any investment Expert or user/investor.
              </p>
              <p>
                Pvot does not give any assurance or fixed return to the investor/user at any point of time or send
                trading call through SMS, call or any other means. Pvot does not give any assurance or fixed return to
                the investor at any point of time.
              </p>
              <p>
                The Website is a platform that facilitates an Investor to interact with various Experts for their
                information purpose through the communication and information medium on the Website. Pvot is not and
                cannot be a party to or not control in any manner on how the Investors act upon the activities performed
                by the Experts. The Investor may be required to pay a Fee to view the activity published by the Experts.
                It is hereby clarified that the activity Info published by Pvot are not in any manner published to
                entice the Investors for to take any actions or mimic the activities of the Experts. The profile details
                of the expert is just a historical representation of the accuracy (not accounting for liquidity and
                market depth) of the activity published by an Expert. Pvot in no manner represents or warrants the
                accuracy of the published activity. The Investors are required to independently evaluate the activity
                and act upon the same at the sole risk of the Investors.
              </p>
              <p>
                Pvot does not make any representation or Warranty as to specifics (such as any kind of profit accuracy
                of market call, etc.) of the activity or the Experts or services proposed to be sold or offered to be
                sold or purchased on the Website. PVOT does not implicitly or explicitly support or endorse any activity
                of trade or recommend any investor action.
              </p>
              <p>
                The profile detail information is not to be construed as an offer to buy /sell or the solicitation of an
                offer to buy / sell any security upon any activity in any jurisdiction where such offer or solicitation
                would be illegal. The activities do not constitute a personal recommendation or take into account the
                particular investment objectives, financial situations, risk profile and needs of individual clients.
              </p>
              <p>
                Website may use cookies. By using our website, you undertake, confirm and agree to these terms of use.
                Your consent is implied to our use of Cookies Policy in accordance with the terms of our Privacy Policy.
              </p>
              <p>
                Pvot may terminate any User's access to the Site or any part thereof at any time and for any reason
                without any notice.
              </p>
              <p>
                Pvot does not give any warranty for accuracy of information, software, database or other system or
                functionality of website.
              </p>
              <p>
                Pvot may change or discontinue any aspect of the Site at any time, including, its content or features.
              </p>
              <p>
                All contents on the Site are the exclusive property of Pvot except third-party content. The software,
                text, images, graphics, video and audio used on the Site belong to or are licensed to Pvot or its
                vendors and affiliates. No material from the Site may be copied, modified, reproduced, republished,
                uploaded, transmitted, posted or distributed in any form without prior written permission from Pvot. All
                rights not expressly granted herein are reserved. Unauthorized use of the materials appearing on the
                Site may violate copyright, trademark and other applicable laws, and could result in criminal or civil
                penalties. You are granted a non-exclusive, non-transferable, limited right to access the Site and avail
                the services provided by Pvot on the Website. To know the detailed terms and conditions applicable to
                the Intellectual Property available on the Website Users are requested to go through the Website Terms
                and Conditions.
              </p>
              <p>
                Pvot does not make any warranties, express or implied, with respect to any service, information, data,
                software, system, functionality, statements or products made available on the Site. The information
                contained in the Site has been obtained from sources believed to be reliable. The Site, and all content,
                materials, information, software and services provided on the Site, are provided on an "as is" and "as
                available" basis.
              </p>
              <p>
                Pvot does not warrant that the Site will operate error-free or that the Site and its servers are free of
                computer viruses or other harmful mechanisms. If your use of the Site or content therein results in the
                need for servicing or replacing equipment or data, Pvot is not responsible for any such costs. Site and
                content are provided on an "as/is" basis without any warranties of any kind. Pvot makes no warranties
                about the accuracy, reliability, completeness, or timeliness of the content, services, software, text,
                graphics, and links.
              </p>
              <p>
                Pvot shall not be liable for any damage to your computer system or loss of data that results from the
                download of any content, materials, and information from the Site or use of any software, systems,
                functionality, or other services on the Site. Under no circumstances will Pvot be liable in any way for
                any content, including, but not limited to, inaccurate, false, incomplete, threatening, defamatory,
                obscene, offensive, illegal content, infringement of other’s rights including intellectual property
                rights, for any errors or omissions in any content, or for any loss or damage of any kind incurred as a
                result of the use of any content posted or uploaded. Further, under no circumstances, Pvot shall be
                liable for any unlawful act of the User or its affiliates, relatives, employees, agents including misuse
                of any data, unfair trade practices, fraud, cybersquatting, hacking and other cybercrimes. In no event
                shall Pvot be liable for damages of any kind, including, direct, incidental or consequential damages
                (including, but not limited to, damages for loss of profits, business interruption and loss of programs
                or information) arising out of the use of or inability to use the Site, or any information provided
                therein, or any claim attributable to errors, omissions or other inaccuracies in the Site.
              </p>
              <p>
                You may not send, submit, post, or otherwise transmit, material or messages that contain software virus,
                or any other files that are designed to corrupt, destroy, and negatively affect in any manner
                whatsoever, any electronic equipment in connection with the use of the Site, or other user's ability to
                use the Site.
              </p>
              <p>
                You may not conduct any systematic or automated data collection activities (including scraping, data
                mining, data extraction and data harvesting) on or in relation to our website without our express
                written consent.
              </p>
              <p>
                You may not use our website or our ’s website to transmit or send unsolicited commercial communications
                except market research related data/documents.
              </p>
              <p>
                For availing the service/platform under our website, registration is required. You will get a password
                and account information upon completing the registration on the Site. You are responsible for
                maintaining the confidentiality of the password and account and are fully responsible for all activities
                that occur under your password or account. By registering, you agreed to these terms of use in addition
                to any other specific terms which shall be posted at an appropriate location of the Site. To access
                these services, you will be asked to enter your individual Username and Password.
              </p>
              <p>Therefore, we do not permit </p> <br></br>
              <ul>
                <li>Any other person sharing your Username and Password</li>
                <li>
                  Any part of the Site being cached in proxy servers and accessed by individuals who have not registered
                  with the Site as users iii) Access through a single User Name and Password being made available to
                  multiple users on a network.
                </li>
              </ul>
              <p>
                You shall be responsible for maintaining the confidentiality of your Display Name and Password and you
                shall be also responsible for all activities that occur under your Display Name and Password. You agree
                that in case of any information you have provided is found to be untrue, inaccurate, or incomplete or
                not current or we have reasonable grounds to suspect that such information is untrue, inaccurate, not
                current or incomplete, or not in accordance with these Terms of Use, we shall have the right to
                indefinitely suspend or terminate or block your access to the Website.
              </p>
              <p>
                Whenever we reasonably believe that a Username and Password are being used / misused in any manner as
                clarified above, we reserve the right to cancel your access right to our website/application immediately
                without any notice or block access to all users from that IP address.
              </p>
              <p>
                You specifically agree that Pvot shall not be responsible for unauthorized access to or alteration of
                your transmissions or data, any material or data sent or received or not sent or received through the
                Site.
              </p>
              <p>
                The Site may be used only for lawful purposes. Pvot specifically prohibits any other use of the Site,
                and all Users agree not to i) Post or submit on the website any incomplete, false or inaccurate report
                or biographical information or information which is not your own; ii) Send unsolicited mail or e-mail,
                making unsolicited phone calls or send unsolicited faxes regarding promotions and/or advertising of
                products or services to a user of the Site; iii) Delete or revise any material posted by any other
                person or entity; iv) Take any action that imposes an unreasonable or disproportionately large load on
                the Site's infrastructure; v) Attempt to decipher, decompile, disassemble or reverse engineer any of the
                software comprising or in any way making up a part of the Site; vi) Aggregate, copy or duplicate in any
                manner any of the content or information available from the Site.
              </p>
              <p>
                You agree not to use / insert any of the User's URL, weblink, email address and website while accessing
                any material on the Site.
              </p>
              <p>
                On non-conformance by users of any of the aforesaid terms, Pvot may in its sole discretion, restrict or
                terminate the offending User's ability to access the Site and determine whether to take any other
                actions i.e. whether to remove or request the removal of the User’s content. Pvot shall have no
                liability or responsibility whatsoever to Users for performance or non-performance of such activities.
              </p>
              <p>
                Pvot with its sole discretion reserves the right to investigate and take legal action against anyone who
                engages in any illegal or prohibited conduct or otherwise violates these Terms of Use, including without
                limitation, removing the User content from the Site and/or terminating the offending User's ability to
                access the Site and/or use services therein. Pvot may take any other action with respect to User content
                or User actions that it deems necessary or appropriate if it believes that it may create liability for
                Pvot or may cause Pvot to lose (in whole or in part) the services of its ISPs or other suppliers.
              </p>
              <p>
                The User hereby specifically agrees to comply with the requirements of the Information Technology Act,
                2000 along with rules, regulations, guidelines, bye laws and notifications made thereunder. The user
                also undertakes that the content provided by him/her is not defamatory, obscene, threatening, abusive or
                hateful. You shall alone be responsible for all your acts, deeds and things and that you shall also be
                liable individually for civil and criminal liability arising thereunder or under any other law for the
                time being in force.
              </p>
              <p>
                Failure or delay by Pvot in exercising any right, power or privilege under the Terms of Use will not
                operate as a waiver of it, nor will any single or partial exercise of it preclude any further exercise
                or the exercise of any right, power or privilege under the Terms of Use.
              </p>
              <p>
                If the Pvot website provides links to web sites and access to content, products and services from third
                parties, including users, advertisers, affiliates and sponsors of the Site, you agree that Pvot is not
                responsible for the availability of, and content provided on third party’s web sites or content. You are
                requested to peruse the policies posted by other web sites regarding privacy and other topics before
                use. Pvot is not responsible for third party content accessible through the Site, including opinions,
                advice, statements and advertisements, and Investor shall bear all risks associated with the use of such
                content. Pvot is not responsible for any loss or damage of any sort which User may incur from dealing
                with any third party.
              </p>
              <p>
                The Website is controlled, operated and administered by Pvot from its offices within India. Pvot makes
                no representation that Materials on this site are appropriate or available for use at any other
                location(s) outside India. Any access to this site from territories where their contents are illegal is
                prohibited. You may not use the site or export the materials in violation of any applicable export laws
                and regulations. If you access this site from a location outside India, you are responsible for
                compliance with all local laws.
              </p>
              <p>
                As part of the necessary process to set up an account on the Site (an "Account") and obtain access to
                certain parts of the Services, you will be required to provide your full name, email address, password,
                and phone number (the "Registration Credentials"). You must ensure that your Registration Credentials
                are accurate, truthful and updated. We reserve the right to block the creation of your Account based on
                our inability to confirm the authenticity of your Registration Credentials.
              </p>
              <p>
                Unless you log-in to your Account via a Third-Party Account, please note that your email address and
                password which you provide as part of the Registration Credentials will be used to login into your
                Account. You will be solely responsible for maintaining the confidentiality of your email address and
                password and must immediately notify us of any unauthorized use of your Account. You are solely
                responsible for all activity and usage on your Account, including, but not limited to, use of the
                Account by any third party authorized by you to use your email address and password. You have to create
                and maintain different Accounts to access different Services at any time.
              </p>
              <p>
                Nothing contained on the Site may be construed as granting, by implication, estoppels, or otherwise, any
                license or right to use any trademark without the written permission of Pvot or any third party that may
                own the trademarks. Your use of trademarks, or any other content/concept of the Site, except as provided
                herein, is strictly prohibited.
              </p>
              <p>
                You undertake and agree to fully indemnify, defend and hold harmless to Pvot, its corporate affiliates
                and their respective officers, directors and employees from all claims, demands, liabilities, damages,
                losses, costs and expenses, including legal fees and other charges whatsoever, that may arise as a
                result of: (i) any breach of these Terms and Conditions by you or (ii) violation by you of any law or
                the rights of any third party. Without prejudice to any other rights in these Terms and Conditions, if
                you breach in whole or in part any provision contained herein, Pvot or any of its corporate affiliates
                or which provides Services to you, reserves the right to take appropriate action as it deems fit,
                including (but not limited to) terminating any agreement in place with you, terminating or blocking the
                Services offered to you via the Site and/or taking legal action against you.
              </p>
              <p>
                In case of any dispute that may arise, you agree that you shall refer the dispute for resolution through
                arbitration proceeding under the Sole arbitrator appointed from the Panel of Arbitrators of Pvot. The
                seat of arbitration shall exclusively be Bangalore. All the arbitration proceeding to resolve the
                dispute will be carried out as per the Arbitration & Conciliation Act 1996 as amended up to date. The
                Arbitration Award will be final and binding on you.
              </p>
              <p>
                These Terms and Conditions shall be construed and interpreted in accordance with the laws of Republic of
                India and the courts at Bangalore shall have the exclusive jurisdiction to entertain and try any matter
                arising out of this Agreement or any agreement(s) thereunder, without conflicts of law thereof. This is
                the case regardless of whether you reside or transact business with Pvot anywhere else in the world.
              </p>
              <p>
                If any part of these Terms and Conditions are held unlawful, void or unenforceable, that part will be
                deemed severable and will not affect the validity and enforceability of any remaining provisions.
              </p>
              <p>
                You are legally bound to comply with law governing the securities market. Further you are also
                responsible to comply with each and every regulatory provision being in force from time to time.
              </p>
              <p>
                The Terms of Use shall be governed by the Laws of India. The Courts of law at Bangalore shall have
                exclusive jurisdiction over any disputes arising under the Terms of Use.
              </p>
              <p>
                The Experts shall confirm that you will not join or become part of any website/application/mobile
                app/platform/aggregator other than Pvot which provide similar services (where one or more Experts
                provide access to real time activity to multiple Investors). However, the Experts are free to
                share/sell/offer your product/market research data/documents/trading call/tips to individual
                person/investor directly.
              </p>
              <p>
                The Experts undertake and agree to indemnify and not hold Pvot, its officers, employees, from any claim,
                demand or damage, including reasonable attorney’s fees, asserted by any third party or any regulatory
                body or administrative body of the government due to or arising out of your use of or conduct on the
                Site. Pvot reserves the right to disclose any personal information about you and your uses of the Site
                including its contents, without your prior permission for its own uses or others. Further, Pvot may also
                share your personal information if necessary to i) conform to legal requirements or comply with legal
                processes; ii) protect and defend the rights or property of Pvot; iii) enforce the Terms of Use; or iv)
                act to protect the interest of its Users, members or others.
              </p>
              <p>
                Any information provided by you may be shared with any third party or user as per discretion of Pvot. We
                reserve the right to use your information to provide the Investor a more personalized online experience.
              </p>
              <p>
                The Experts shall be responsible for your offer/research data/report/documents/trading call/tips/
                service(s)/ activity provided by you through our platform.
              </p>
              <p>
                The Experts agree, consent and confirm that Pvot can use your logo, name on its website, application,
                mobile app, promotional/marketing material, social media marketing, digital campaign, whether in written
                or oral format etc. as and when Pvot deems fit or required for business promotion or procurement. You
                will not demand any pay-out from Pvot for using your name or logo.
              </p>
              <p>
                Pvot shall have the right to use its algorithms or use any such method or process to determine the
                quality of the performance determined through the activity undertaken by an Expert and shall publish the
                same on the Website alongside the details of the Expert. Pvot shall have the absolute discretion to
                determine the performance of the Expert on the Website and shall have the right to alter the manner in
                which the Experts information is displayed within the Website. Pvot shall not be liable for any loss of
                ranking in search results, quality of performance, direct loss, indirect loss, remote loss that may
                occur to the Expert due the actions of the Expert on the Website or as may occur due to any decision or
                action take by Pvot as per the Pvot Policies.
              </p>
              <p>Payment terms: Pay per advice model</p> <br></br>
              <ul>
                <li>Experts are paid only for profit-generating advice/recommendation</li>
                <li>
                  There will be GST 18% deducted from the payment and also 15% commission for Pvot prior to any payment
                  made to the Experts
                </li>
                <li>
                  The Experts shall be paid every Tuesday based on the earnings of the Expert for the preceding 7 days.
                </li>
              </ul>
            </Row>
            <Row>
              <h6>SPECIFIC TERMS OF USE FOR THE INVESTORS</h6>
            </Row>
            <Row>
              <p>
                For availing the services under the Site, registration by the User is required. You will have a password
                and account designation upon completing the registration on the Site. You are responsible for
                maintaining the confidentiality of the password and account and are fully responsible for all activities
                that occur under your password or account. By registering, you agree to the following terms in addition
                to any other specific terms which shall be posted at an appropriate location of the Site. Each
                registration is for a single individual user only. To access these services, you will be asked to enter
                your individual Username and Password. Therefore, we do not permit i) Any other person sharing your
                Username and Password ii) Any part of the Site being cached in proxy servers and accessed by individuals
                who have not registered with Site as users iii) Access through a single Username and Password being made
                available to multiple users on a network.
              </p>
              <p>
                As part of the process necessary to set up an account on the Site (an "Account") and obtain access to
                certain parts of the Services, you will be required to either provide your full name, email address,
                password, and phone number (the "Registration Credentials"). You must ensure that your Registration
                Credentials are accurate, truthful and updated. We reserve the right to block the creation of your
                Account based on our inability to confirm the authenticity of your Registration Credentials.
              </p>
              <p>
                You shall be responsible for maintaining the confidentiality of your Display Name and Password and you
                shall be responsible for all activities that occur under your Display Name and Password. You agree that
                if You provide any information that is untrue, inaccurate, not current or incomplete or We have
                reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or
                not in accordance with these Terms of Use, We shall have the right to indefinitely suspend or terminate
                or block access of your membership on the Website and refuse to provide You with access to the Website.
              </p>
              <p>
                Pvot is a platform that aims to establish a link between Experts and Investors. The Investors hereby
                acknowledge that Pvot is not a SEBI registered Investment Expert or Research Analyst or Independent
                Research Analyst. The Investors hereby also agree and acknowledge that Investors have the responsibility
                to conduct their enquiry to determine the nature of the Experts on the platform and their qualifications
                and registrations under all applicable laws which the Experts shall disclose within their profile. The
                Investors understand the volatile nature of the securities markets and acknowledge that the activity
                data provided by the Experts is being provided by the Experts in their professional capacity and that
                Pvot has no role to play in the kind of activity published on the Website. The Investors shall evaluate
                the activity data obtained by the Investors through the Website and make an independent decision on
                whether they choose to act on the same.
              </p>
              <p>
                Neither the Experts nor Pvot in any way guarantee the accuracy of the activity published on the Website.
                Pvot shall not be liable for any incurred loss, future loss, direct loss, indirect loss, remote loss or
                any other form of loss incurred by the Investor from acting on the activity published on the Website or
                such loss incurred by the Investor due to the use of the Website.
              </p>
              <p>
                Pvot does not give guarantee of showing activity or maintaining activity from each and every registered
                Expert on its platform. The Experts are have the right to publish the activity at such intervals as may
                be determined by the Expert.
              </p>
              <p>
                The Website is a platform that investors can use to meet and interact with various market/technical
                experts for their investment purpose. Pvot is not and cannot be a party to or control in any manner or
                any transaction between the Investors or with Expert.
              </p>
            </Row>
          </div>
        </div>
      </Grow>
    );
  }
}

export default Terms;
