/**
 * Auth
 */

export const DEVICE_TOKEN = 'DEVICE_TOKEN';

export const USER_AUTH_START = 'USER_AUTH_START';
export const USER_AUTH = 'USER_AUTH';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';
export const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE';
export const USER_AUTH_MID = 'USER_AUTH_MID';

export const USER_AUTH_ALERT_SHOW_HIDE_DANGER = 'USER_AUTH_ALERT_SHOW_HIDE_DANGER';
export const USER_AUTH_ALERT_SHOW_HIDE_DANGER_DISMISS = 'USER_AUTH_ALERT_SHOW_HIDE_DANGER_DISMISS';
export const SWITCH_TO_OTP = 'SWITCH_TO_OTP';

export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN = 'SIGNIN';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const SIGNIN_MID = 'SIGNIN_MID';
export const SIGNIN_ALERT_SHOW_HIDE_DANGER = 'SIGNIN_ALERT_SHOW_HIDE_DANGER';
export const SIGNIN_ALERT_SHOW_HIDE_DANGER_DISMISS = 'SIGNIN_ALERT_SHOW_HIDE_DANGER_DISMISS';

export const SET_GROUP = 'SET_GROUP';
export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_MID = 'SIGNUP_MID';
export const SIGNUP_ALERT_SHOW_HIDE_DANGER = 'SIGNUP_ALERT_SHOW_HIDE_DANGER';
export const SIGNUP_ALERT_SHOW_HIDE_DANGER_DISMISS = 'SIGNUP_ALERT_SHOW_HIDE_DANGER_DISMISS';

export const VERIFY_OTP_START = 'VERIFY_OTP_START';
export const VERIFY_OTP = 'VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';
export const VERIFY_OTP_MID = 'VERIFY_OTP_MID';
export const VERIFY_OTP_ALERT_SHOW_HIDE_DANGER = 'VERIFY_OTP_ALERT_SHOW_HIDE_DANGER';
export const VERIFY_OTP_ALERT_SHOW_HIDE_DANGER_DISMISS = 'VERIFY_OTP_ALERT_SHOW_HIDE_DANGER_DISMISS';

export const RESEND_OTP_START = 'RESEND_OTP_START';
export const RESEND_OTP = 'RESEND_OTP';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_FAILURE = 'RESEND_OTP_FAILURE';
export const RESEND_OTP_MID = 'RESEND_OTP_MID';
export const RESEND_OTP_ALERT_SHOW_HIDE_DANGER = 'RESEND_OTP_ALERT_SHOW_HIDE_DANGER';
export const RESEND_OTP_ALERT_SHOW_HIDE_DANGER_DISMISS = 'RESEND_OTP_ALERT_SHOW_HIDE_DANGER_DISMISS';

export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const FORGOT_PASSWORD_MID = 'FORGOT_PASSWORD_MID';
export const FORGOT_PASSWORD_ALERT_SHOW_HIDE_DANGER = 'FORGOT_PASSWORD_ALERT_SHOW_HIDE_DANGER';
export const FORGOT_PASSWORD_ALERT_SHOW_HIDE_DANGER_DISMISS = 'FORGOT_PASSWORD_ALERT_SHOW_HIDE_DANGER_DISMISS';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const RESET_PASSWORD_MID = 'RESET_PASSWORD_MID';
export const RESET_PASSWORD_ALERT_SHOW_HIDE_DANGER = 'RESET_PASSWORD_ALERT_SHOW_HIDE_DANGER';
export const RESET_PASSWORD_ALERT_SHOW_HIDE_DANGER_DISMISS = 'RESET_PASSWORD_ALERT_SHOW_HIDE_DANGER_DISMISS';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const LOGOUT_MID = 'LOGOUT_MID';
export const LOGOUT_ALERT_SHOW_HIDE_DANGER = 'LOGOUT_ALERT_SHOW_HIDE_DANGER';
export const LOGOUT_ALERT_SHOW_HIDE_DANGER_DISMISS = 'LOGOUT_ALERT_SHOW_HIDE_DANGER_DISMISS';

export const CHANGE_HOME_STATE = 'CHANGE_HOME_STATE';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';

export const CREATE_SUBSCRIPTION_PLAN = 'CREATE_SUBSCRIPTION_PLAN';
export const RESET_ERROR_CREATE_SUBSCRIPTION = 'RESET_ERROR_CREATE_SUBSCRIPTION';

export const CREATE_BANK_ACCOUNT = 'CREATE_BANK_ACCOUNT';
export const SAVE_BANK_ACCOUNT = 'SAVE_BANK_ACCOUNT';
export const ERROR_CREATE_BANK_ACCOUNT = 'ERROR_CREATE_BANK_ACCOUNT';
export const SET_LOADER = 'SET_LOADER';
export const SET_MESSAGE = 'SET_MESSAGE';
export const GET_BANK_DETAILS = 'GET_BANK_DETAILS';

/**
 * Account
 */
export const UPDATE_NAME = 'UPDATE_NAME';
export const SET_UPDATED_NAME = 'SET_UPDATED_NAME';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const SET_UPDATED_EMAIL = 'SET_UPDATED_EMAIL';
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
export const SET_UPDATED_PROFILE_IMAGE = 'SET_UPDATED_PROFILE_IMAGE';
export const GET_ANALYST_DETAILS = 'GET_ANALYST_DETAILS';
export const SET_ANALYST_DETAILS = 'SET_ANALYST_DETAILS';
export const GET_SUBSCRIPTION_PLAN_LIST = 'GET_SUBSCRIPTION_PLAN_LIST';
export const SET_SUBSCRIPTION_PLAN_LIST = 'SET_SUBSCRIPTION_PLAN_LIST';
export const GET_TRADE_LIST = 'GET_TRADE_LIST';
export const SET_TRADE_LIST = 'SET_TRADE_LIST';
export const DELETE_SUBSCRIPTION_PLAN = 'DELETE_SUBSCRIPTION_PLAN';
export const CANCEL_TRADE = 'CANCEL_TRADE';
export const SET_TRADE_ITEM = 'SET_TRADE_ITEM';
export const GET_PROFILE_IMAGE = 'GET_PROFILE_IMAGE';
export const DOCUMENT_UPDATED = 'DOCUMENT_UPDATED';
export const GET_TRADE_COUNTS = 'GET_TRADE_COUNTS';
export const SET_TRADE_COUNTS = 'SET_TRADE_COUNTS';
export const GET_FEED = 'GET_FEED';
export const SET_FEED = 'SET_FEED';
export const GET_SUB_FEED = 'GET_SUB_FEED';
export const SET_SUB_FEED = 'SET_SUB_FEED';
export const GET_FEED_IMAGES = 'GET_FEED_IMAGES';
export const SET_FEED_IMAGES = 'SET_FEED_IMAGES';
export const GET_COMMENTS = 'GET_COMMENTS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const POST_COMMENT = 'POST_COMMENT';
export const GET_SUBSCRIPTION = 'GET_SUBSCRIPTION';
export const SET_SUBSCRIPTION = 'SET_SUBSCRIPTION';
export const GET_PREFERENCES = 'GET_PREFERENCES';
export const GET_PREFERENCES_SUCCESS = 'GET_PREFERENCES_SUCCESS';
export const SET_PREFERENCES = 'SET_PREFERENCES';
export const SET_PREFERENCES_SUCCESS = 'SET_PREFERENCES_SUCCESS';
export const GET_RISK_PROFILE_QUESTIONS = 'GET_RISK_PROFILE_QUESTIONS';
export const GET_RISK_PROFILE_QUESTIONS_SUCCESS = 'GET_RISK_PROFILE_QUESTIONS_SUCCESS';
export const SEND_RISK_PROFILE_ANSWERS = 'SEND_RISK_PROFILE_ANSWERS';
export const SEND_RISK_PROFILE_ANSWERS_SUCCESS = 'SEND_RISK_PROFILE_ANSWERS_SUCCESS';
export const GET_RISK_PROFILING_SCORE_SUCCESS = 'GET_RISK_PROFILING_SCORE_SUCCESS';
export const UPDATE_DEMAT_ACCOUNTS = 'UPDATE_DEMAT_ACCOUNTS';
export const SET_DEMAT_ACCOUNTS = 'SET_DEMAT_ACCOUNTS';
export const SET_UPDATED_DEMAT_ACCOUNTS = 'SET_UPDATED_DEMAT_ACCOUNTS';

/**
 * Place trade
 */
export const PLACE_TRADE = 'PLACE_TRADE';
export const GET_AVAILABLE_TRADE_BALANCE = 'GET_AVAILABLE_TRADE_BALANCE';
export const SET_AVAILABLE_TRADE_BALANCE = 'SET_AVAILABLE_TRADE_BALANCE';
export const FETCH_INSTRUMENT_TOKENS = 'FETCH_INSTRUMENT_TOKENS';
export const SAVE_INSTRUMENT_TOKENS = 'SAVE_INSTRUMENT_TOKENS';
export const CLEAR_INSTRUMENT_TOKENS = 'CLEAR_INSTRUMENT_TOKENS';

/**
 * Upload Document
 */
export const UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT';

/**
 * Analyst update
 */
export const UPDATE_ANALYST_BASIC_DETAILS = 'UPDATE_ANALYST_BASIC_DETAILS';
export const GET_ANALYST_FOLLOWERS = 'GET_ANALYST_FOLLOWERS';
export const SET_ANALYST_FOLLOWERS = 'SET_ANALYST_FOLLOWERS';
export const GET_ANALYST_SUBSCRIBERS = 'GET_ANALYST_SUBSCRIBERS';
export const SET_ANALYST_SUBSCRIBERS = 'SET_ANALYST_SUBSCRIBERS';

/**
 * Analyst Portfolio
 */
export const CREATE_ANALYST_PORTFOLIO = 'CREATE_ANALYST_PORTFOLIO';
export const SET_ANALYST_PORTFOLIO = 'SET_ANALYST_PORTFOLIO';
export const GET_ANALYST_PORTFOLIO = 'GET_ANALYST_PORTFOLIO';

/**
 * ********************************** GET WEBINAR LIST ******************************************
 */
export const GET_WEBINAR_LIST = 'GET_WEBINAR_LIST';
export const SAVE_WEBINAR_LIST = 'SAVE_WEBINAR_LIST';

/**
 * ********************************** USER ACTIONS ******************************************
 */

export const FETCH_ANALYSTS_FOR_SUBSCRIPTION = 'FETCH_ANALYSTS_FOR_SUBSCRIPTION';
export const SAVE_ANALYSTS_FOR_SUBSCRIPTION = 'SAVE_ANALYSTS_FOR_SUBSCRIPTION';
export const APPLY_ANALYST_BROWSE_FILTER = 'APPLY_ANALYST_BROWSE_FILTER';
export const SET_ANALYST_BROWSE_LIST = 'SET_ANALYST_BROWSE_LIST';
export const SET_FILTER_VALUES = 'SET_FILTER_VALUES';
export const FETCH_PERFORMANCE_AND_TRANSACTIONS_DATA = 'FETCH_PERFORMANCE_AND_TRANSACTIONS_DATA';
export const SAVE_PERFORMANCE_AND_TRANSACTIONS_DATA = 'SAVE_PERFORMANCE_AND_TRANSACTIONS_DATA';
export const FETCH_USER_CARDS = 'FETCH_USER_CARDS';
export const SAVE_USER_CARDS = 'SAVE_USER_CARDS';
export const FETCH_ALL_WEBINARS = 'FETCH_ALL_WEBINARS';
export const SAVE_ALL_WEBINARS = 'SAVE_ALL_WEBINARS';
export const GET_ANALYST_SUBSCRIPTION_PLAN = 'GET_ANALYST_SUBSCRIPTION_PLAN';
export const SET_ANALYST_SUBSCRIPTION_PLAN = 'SET_ANALYST_SUBSCRIPTION_PLAN';
export const GET_PAYMENT_SUBSCRIPTION_LINK = 'GET_PAYMENT_SUBSCRIPTION_LINK';
export const SET_PAYMENT_SUBSCRIPTION_LINK = 'SET_PAYMENT_SUBSCRIPTION_LINK';
export const GET_RECENTLY_CLOSED_TRADES = 'GET_RECENTLY_CLOSED_TRADES';
export const SET_RECENTLY_CLOSED_TRADES = 'SET_RECENTLY_CLOSED_TRADES';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_KYC_DETAILS = 'SET_KYC_DETAILS';
export const SET_KYC_DETAILS_SUCCESS = 'SET_KYC_DETAILS_SUCCESS';
export const SET_ANALYST_MESSAGE = 'SET_ANALYST_MESSAGE';
export const GET_REFERRAL_CODE = 'GET_REFERRAL_CODE';
export const SET_REFERRAL_CODE = 'SET_REFERRAL_CODE';
export const CHECK_REFERRAL_CODE = 'CHECK_REFERRAL_CODE';
export const GET_REFERRED_BY = 'GET_REFERRED_BY';
export const GET_BLOG_LIST = 'GET_BLOG_LIST';
export const SET_BLOG_LIST = 'SET_BLOG_LIST';
export const GET_BLOG_LIST_DESKTOP = 'GET_BLOG_LIST_DESKTOP';
export const SET_BLOG_LIST_DESKTOP = 'SET_BLOG_LIST_DESKTOP';
export const GET_BLOG_DETAIL = 'GET_BLOG_DETAIL';
export const SET_BLOG_DETAIL = 'SET_BLOG_DETAIL';

export const GET_BLOG_COMMENTS = 'GET_BLOG_COMMENTS';
export const SET_BLOG_COMMENTS = 'SET_BLOG_COMMENTS';
export const SEND_BLOG_COMMENT = 'SEND_BLOG_COMMENT';
// follow and feed

export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';

export const LIKE = 'LIKE';
export const UNLIKE = 'UNLIKE';

export const TOGGLE_BLOG_LIKE = 'TOGGLE_BLOG_LIKE';

/**
 * ********************************** Allow Trade Entry ******************************************
 */
export const ALLOW_ENTRY = 'ALLOW_ENTRY';
export const SET_ALLOW_ENTRY = 'SET_ALLOW_ENTRY';

/**
 * ********************************** Analyst Leaderboard ******************************************
 */
export const GET_ANALYST_LEADERBOARD = 'GET_ANALYST_LEADERBOARD';
export const SET_ANALYST_LEADERBOARD = 'SET_ANALYST_LEADERBOARD';

/**
 * ********************************** SET LOADING ******************************************
 */
export const SET_LOADING = 'SET_LOADING';

/**
 * ********************************** Page Switch ******************************************
 */
export const SWITCH_TO_PROFILE_DISPLAY = 'SWITCH_TO_PROFILE_DISPLAY';
export const SWITCH_TO_ACCOUNT_DISPLAY = 'SWITCH_TO_ACCOUNT_DISPLAY';
